import { ImporterPlugin } from '../types';

export const IMPORTERS: ImporterPlugin[] = [
  {
    id: 'goodreads',
    name: 'Goodreads',
    descriptionKey: 'goodreadsDesc',
    icon: 'book-open',
    targetPlatform: 'Bookstr & NIP-51 Clients',
    targetKindDescription: 'NIP-51 (Kind 30003), Bookstr (Kinds 10073-10075) & Kind 31985',
    status: 'active',
    acceptedFileTypes: ['.csv'],
    parseFile: async () => [],
    buildEvent: () => ({ kind: 30003, tags: [], content: '', created_at: 0, pubkey: '' }),
  },
  {
    id: 'blogs',
    name: 'WordPress (WXR XML)',
    descriptionKey: 'blogsDesc',
    icon: 'file-text',
    targetPlatform: 'Habla & Yakihonne',
    targetKindDescription: 'NIP-23 Long-Form Articles (Kind 30023)',
    status: 'active',
    acceptedFileTypes: ['.xml', '.wxr'],
    parseFile: async () => [],
    buildEvent: () => ({ kind: 30023, tags: [], content: '', created_at: 0, pubkey: '' }),
  },
  {
    id: 'gists',
    name: 'GitHub Gists',
    descriptionKey: 'gistsDesc',
    icon: 'code',
    targetPlatform: 'Nostr Code Clients & Neovim',
    targetKindDescription: 'NIP-C0 Snippets (Kind 1337) & NIP-44 Encrypted (Kind 30078)',
    status: 'active',
    acceptedFileTypes: ['.json', '.js', '.ts', '.py', '.rs', '.go', '.sh', '.md', '.txt'],
    parseFile: async () => [],
    buildEvent: () => ({ kind: 1337, tags: [], content: '', created_at: 0, pubkey: '' }),
  },
  {
    id: 'imdb',
    name: 'IMDb',
    descriptionKey: 'imdbDesc',
    icon: 'film',
    targetPlatform: 'Nostr Film Trackers',
    targetKindDescription: 'NIP-51 Lists & Kind 1985 Reviews',
    status: 'coming-soon',
    acceptedFileTypes: ['.csv'],
    parseFile: async () => [],
    buildEvent: () => ({ kind: 30001, tags: [], content: '', created_at: 0, pubkey: '' }),
  },
  {
    id: 'letterboxd',
    name: 'Letterboxd',
    descriptionKey: 'letterboxdDesc',
    icon: 'clapperboard',
    targetPlatform: 'Nostr Film Trackers',
    targetKindDescription: 'NIP-51 Lists & Rating Events',
    status: 'coming-soon',
    acceptedFileTypes: ['.csv', '.zip'],
    parseFile: async () => [],
    buildEvent: () => ({ kind: 30001, tags: [], content: '', created_at: 0, pubkey: '' }),
  },
  {
    id: 'twitter',
    name: 'Twitter / X',
    descriptionKey: 'twitterDesc',
    icon: 'twitter',
    targetPlatform: 'Damus, Amethyst, Primal',
    targetKindDescription: 'NIP-01 Short Notes (Kind 1)',
    status: 'coming-soon',
    acceptedFileTypes: ['.js', '.json', '.zip'],
    parseFile: async () => [],
    buildEvent: () => ({ kind: 1, tags: [], content: '', created_at: 0, pubkey: '' }),
  },
  {
    id: 'instagram',
    name: 'Instagram',
    descriptionKey: 'instagramDesc',
    icon: 'camera',
    targetPlatform: 'Blossom / Nostr Picture Posts',
    targetKindDescription: 'NIP-68 Picture Posts (Kind 20)',
    status: 'coming-soon',
    acceptedFileTypes: ['.zip', '.json'],
    parseFile: async () => [],
    buildEvent: () => ({ kind: 20, tags: [], content: '', created_at: 0, pubkey: '' }),
  },
  {
    id: 'spotify',
    name: 'Spotify',
    descriptionKey: 'spotifyDesc',
    icon: 'music',
    targetPlatform: 'Wavelake & Stemstr',
    targetKindDescription: 'NIP-51 Music Playlists (Kind 30001)',
    status: 'coming-soon',
    acceptedFileTypes: ['.json', '.csv'],
    parseFile: async () => [],
    buildEvent: () => ({ kind: 30001, tags: [], content: '', created_at: 0, pubkey: '' }),
  },
];
